version: '3'
services:
  db:
    image: postgres:13.0
    volumes:
<<<<<<< HEAD
      - ~/volume/db:/var/lib/postgresql/data
=======
      - ~/volume/db2:/var/lib/postgresql/data
>>>>>>> develop
    environment:
      POSTGRES_PASSWORD: 'postgres'
  web:
    build: .
    command: bash -c "bundle install  && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
<<<<<<< HEAD
      - "5000:3000"
=======
      - "3333:3000"
>>>>>>> develop
    depends_on:
      - db
    environment:
      RAILS_ENV: production

